[package]
name = "vercel_lambda"
version = "0.3.0"

authors = ["Vercel <support@vercel.com>"]
description = "Rust runtime for Vercel Functions."
documentation = "https://docs.rs/vercel_lambda"
homepage = "https://github.com/vercel-community/rust"
keywords = ["Vercel", "Rust", "Serverless", "Functions"]
license = "MIT"
repository = "https://github.com/vercel-community/rust"

edition = "2021"

include = [
  "src/*.rs",
  "Cargo.toml",
]

[features]
default = ["runtime"]

runtime = ["tokio"]

[dependencies]
base64 = "0.13"
http = "0.2"
lambda_runtime = "0.7"
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
tokio = {version = "1.23", optional = true, features = ["full"]}

[dev-dependencies]
anyhow = "1"
tokio = "1.17"
